// This file is generated by npm run supabase:types.
// Do not edit it by hand. Update Supabase migrations/schema, then regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      analytical_sessions: {
        Row: {
          created_at: string
          document_id: string
          id: string
          phases: Json
          source_issue: string
        }
        Insert: {
          created_at?: string
          document_id: string
          id?: string
          phases?: Json
          source_issue: string
        }
        Update: {
          created_at?: string
          document_id?: string
          id?: string
          phases?: Json
          source_issue?: string
        }
        Relationships: [
          {
            foreignKeyName: "analytical_sessions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_briefings: {
        Row: {
          ai_summary: string
          created_at: string
          date: string
          id: string
          source: string
          title: string
          url: string
        }
        Insert: {
          ai_summary: string
          created_at?: string
          date?: string
          id?: string
          source: string
          title: string
          url: string
        }
        Update: {
          ai_summary?: string
          created_at?: string
          date?: string
          id?: string
          source?: string
          title?: string
          url?: string
        }
        Relationships: []
      }
      documents: {
        Row: {
          content_markdown: string
          created_at: string
          id: string
          source_module: string
          title: string
          topic_id: string | null
          updated_at: string
        }
        Insert: {
          content_markdown: string
          created_at?: string
          id?: string
          source_module: string
          title: string
          topic_id?: string | null
          updated_at?: string
        }
        Update: {
          content_markdown?: string
          created_at?: string
          id?: string
          source_module?: string
          title?: string
          topic_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
        ]
      }
      rag_books: {
        Row: {
          author: string | null
          created_at: string | null
          id: string
          title: string
          total_chunks: number | null
        }
        Insert: {
          author?: string | null
          created_at?: string | null
          id?: string
          title: string
          total_chunks?: number | null
        }
        Update: {
          author?: string | null
          created_at?: string | null
          id?: string
          title?: string
          total_chunks?: number | null
        }
        Relationships: []
      }
      rag_chunks: {
        Row: {
          book_id: string
          chapter_index: number | null
          chapter_summary: string | null
          chapter_title: string | null
          chunk_index: number | null
          content: string
          created_at: string | null
          embedding: string | null
          fts: unknown
          id: string
          part_title: string | null
          word_count: number | null
        }
        Insert: {
          book_id: string
          chapter_index?: number | null
          chapter_summary?: string | null
          chapter_title?: string | null
          chunk_index?: number | null
          content: string
          created_at?: string | null
          embedding?: string | null
          fts?: unknown
          id?: string
          part_title?: string | null
          word_count?: number | null
        }
        Update: {
          book_id?: string
          chapter_index?: number | null
          chapter_summary?: string | null
          chapter_title?: string | null
          chunk_index?: number | null
          content?: string
          created_at?: string | null
          embedding?: string | null
          fts?: unknown
          id?: string
          part_title?: string | null
          word_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "rag_chunks_book_id_fkey"
            columns: ["book_id"]
            isOneToOne: false
            referencedRelation: "rag_books"
            referencedColumns: ["id"]
          },
        ]
      }
      topics: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          title: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          title: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      hybrid_search: {
        Args: {
          book_uuid_param?: string
          match_count: number
          query_embedding: string
          query_text: string
        }
        Returns: {
          book_id: string
          chapter_title: string
          chunk_index: number
          content: string
          id: string
          similarity: number
        }[]
      }
      search_chunks:
        | {
            Args: {
              book_uuid: string
              match_count?: number
              query_embedding: string
            }
            Returns: {
              chapter_summary: string
              chapter_title: string
              content: string
              id: string
              part_title: string
              similarity: number
            }[]
          }
        | {
            Args: {
              book_uuid_param?: string
              match_count: number
              query_embedding: string
            }
            Returns: {
              chapter_title: string
              chunk_index: number
              content: string
              id: string
              similarity: number
            }[]
          }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
